-- MySQL Script generated by MySQL Workbench
-- Sat Nov 15 12:36:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Genero` (
  `idGenero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Sala` (
  `idSala` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Assento` (
  `idAssento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(3) NOT NULL,
  `Sala_idSala` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAssento`),
  INDEX `fk_Assento_Sala1_idx` (`Sala_idSala`),
  CONSTRAINT `fk_Assento_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `cinema`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Filme` (
  `idFilme` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `sinopse` VARCHAR(100) NOT NULL,
  `duracao` INT(3) NOT NULL,
  `classificacaoIndicativa` INT(2) NOT NULL,
  `Genero_idGenero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFilme`),
  INDEX `fk_Filme_Genero_idx` (`Genero_idGenero`),
  CONSTRAINT `fk_Filme_Genero`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `cinema`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `metodoPagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Trailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Trailer` (
  `idTrailer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `duracao` INT(2) NOT NULL,
  PRIMARY KEY (`idTrailer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Sessao` (
  `idSessao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `formato` VARCHAR(10) NOT NULL,
  `idioma` VARCHAR(10) NOT NULL,
  `Filme_idFilme` INT UNSIGNED NOT NULL,
  `Sala_idSala` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  PRIMARY KEY (`idSessao`),
  INDEX `fk_Sessao_Filme1_idx` (`Filme_idFilme`),
  INDEX `fk_Sessao_Sala1_idx` (`Sala_idSala`),
  CONSTRAINT `fk_Sessao_Filme1`
    FOREIGN KEY (`Filme_idFilme`)
    REFERENCES `cinema`.`Filme` (`idFilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `cinema`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Sessao_has_Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Sessao_has_Assento` (
  `Sessao_idSessao` INT UNSIGNED NOT NULL,
  `Assento_idAssento` INT UNSIGNED NOT NULL,
  `ocupado` TINYINT NOT NULL,
  PRIMARY KEY (`Sessao_idSessao`, `Assento_idAssento`),
  INDEX `fk_Sessao_has_Assento_Assento1_idx` (`Assento_idAssento`),
  INDEX `fk_Sessao_has_Assento_Sessao1_idx` (`Sessao_idSessao`),
  CONSTRAINT `fk_Sessao_has_Assento_Sessao1`
    FOREIGN KEY (`Sessao_idSessao`)
    REFERENCES `cinema`.`Sessao` (`idSessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_has_Assento_Assento1`
    FOREIGN KEY (`Assento_idAssento`)
    REFERENCES `cinema`.`Assento` (`idAssento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Ingresso` (
  `idIngresso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `Sessao_has_Assento_Sessao_idSessao` INT UNSIGNED NOT NULL,
  `Sessao_has_Assento_Assento_idAssento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idIngresso`),
  INDEX `fk_Ingresso_Cliente1_idx` (`Cliente_idCliente`),
  INDEX `fk_Ingresso_Sessao_has_Assento1_idx` (`Sessao_has_Assento_Sessao_idSessao` ASC, `Sessao_has_Assento_Assento_idAssento`),
  CONSTRAINT `fk_Ingresso_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `cinema`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Sessao_has_Assento1`
    FOREIGN KEY (`Sessao_has_Assento_Sessao_idSessao` , `Sessao_has_Assento_Assento_idAssento`)
    REFERENCES `cinema`.`Sessao_has_Assento` (`Sessao_idSessao` , `Assento_idAssento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`Trailer_has_Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`Trailer_has_Sessao` (
  `Trailer_idTrailer` INT UNSIGNED NOT NULL,
  `Sessao_idSessao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Trailer_idTrailer`, `Sessao_idSessao`),
  INDEX `fk_Trailer_has_Sessao_Sessao1_idx` (`Sessao_idSessao`),
  INDEX `fk_Trailer_has_Sessao_Trailer1_idx` (`Trailer_idTrailer`),
  CONSTRAINT `fk_Trailer_has_Sessao_Trailer1`
    FOREIGN KEY (`Trailer_idTrailer`)
    REFERENCES `cinema`.`Trailer` (`idTrailer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trailer_has_Sessao_Sessao1`
    FOREIGN KEY (`Sessao_idSessao`)
    REFERENCES `cinema`.`Sessao` (`idSessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
