-- MySQL Script generated by MySQL Workbench
-- Fri Oct 24 08:29:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `idSala` INT NOT NULL,
  `nome` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Assento` (
  `idAssento` INT NOT NULL,
  `nome` VARCHAR(2) NOT NULL,
  `ocupado` TINYINT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  PRIMARY KEY (`idAssento`),
  INDEX `fk_Assento_Sala1_idx` (`Sala_idSala` ASC) VISIBLE,
  CONSTRAINT `fk_Assento_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `mydb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filme` (
  `idFilme` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `sinopse` VARCHAR(100) NOT NULL,
  `duracao` INT(3) NOT NULL,
  `classificacaoIndicativa` INT(2) NOT NULL,
  `Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`idFilme`),
  INDEX `fk_Filme_Genero_idx` (`Genero_idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Filme_Genero`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `mydb`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `cpf` INT(11) NOT NULL,
  `metodoPagamento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trailer` (
  `idTrailer` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `duracao` INT(2) NOT NULL,
  PRIMARY KEY (`idTrailer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sessao` (
  `idSecao` INT NOT NULL AUTO_INCREMENT,
  `formato` VARCHAR(10) NOT NULL,
  `idioma` VARCHAR(10) NOT NULL,
  `Filme_idFilme` INT NOT NULL,
  `Sala_idSala` INT NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  PRIMARY KEY (`idSecao`),
  INDEX `fk_Sessao_Filme1_idx` (`Filme_idFilme` ASC) VISIBLE,
  INDEX `fk_Sessao_Sala1_idx` (`Sala_idSala` ASC) VISIBLE,
  CONSTRAINT `fk_Sessao_Filme1`
    FOREIGN KEY (`Filme_idFilme`)
    REFERENCES `mydb`.`Filme` (`idFilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `mydb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingresso` (
  `idIngresso` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `Sessao_idSecao` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idIngresso`),
  INDEX `fk_Ingresso_Sessao1_idx` (`Sessao_idSecao` ASC) VISIBLE,
  INDEX `fk_Ingresso_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Ingresso_Sessao1`
    FOREIGN KEY (`Sessao_idSecao`)
    REFERENCES `mydb`.`Sessao` (`idSecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trailer_has_Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trailer_has_Sessao` (
  `Trailer_idTrailer` INT NOT NULL,
  `Sessao_idSecao` INT NOT NULL,
  PRIMARY KEY (`Trailer_idTrailer`, `Sessao_idSecao`),
  INDEX `fk_Trailer_has_Sessao_Sessao1_idx` (`Sessao_idSecao` ASC) VISIBLE,
  INDEX `fk_Trailer_has_Sessao_Trailer1_idx` (`Trailer_idTrailer` ASC) VISIBLE,
  CONSTRAINT `fk_Trailer_has_Sessao_Trailer1`
    FOREIGN KEY (`Trailer_idTrailer`)
    REFERENCES `mydb`.`Trailer` (`idTrailer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trailer_has_Sessao_Sessao1`
    FOREIGN KEY (`Sessao_idSecao`)
    REFERENCES `mydb`.`Sessao` (`idSecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sessao_has_Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sessao_has_Assento` (
  `Sessao_idSecao` INT NOT NULL,
  `Assento_idAssento` INT NOT NULL,
  PRIMARY KEY (`Sessao_idSecao`, `Assento_idAssento`),
  INDEX `fk_Sessao_has_Assento_Assento1_idx` (`Assento_idAssento` ASC) VISIBLE,
  INDEX `fk_Sessao_has_Assento_Sessao1_idx` (`Sessao_idSecao` ASC) VISIBLE,
  CONSTRAINT `fk_Sessao_has_Assento_Sessao1`
    FOREIGN KEY (`Sessao_idSecao`)
    REFERENCES `mydb`.`Sessao` (`idSecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_has_Assento_Assento1`
    FOREIGN KEY (`Assento_idAssento`)
    REFERENCES `mydb`.`Assento` (`idAssento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
