-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 16:14:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema` DEFAULT CHARACTER SET utf8 ;
USE `Cinema` ;

-- -----------------------------------------------------
-- Table `Cinema`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Genero` (
  `idGenero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Sala` (
  `idSala` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Assento` (
  `idAssento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(3) NOT NULL,
  `idSala` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAssento`),
  INDEX `fk_Assento_Sala1_idx` (`idSala`),
  CONSTRAINT `fk_Assento_Sala1`
    FOREIGN KEY (`idSala`)
    REFERENCES `Cinema`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Filme` (
  `idFilme` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `sinopse` VARCHAR(100) NOT NULL,
  `duracao` INT(3) UNSIGNED NOT NULL,
  `classificacaoIndicativa` INT(2) UNSIGNED NOT NULL,
  `idGenero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFilme`),
  INDEX `fk_Filme_Genero_idx` (`idGenero`),
  CONSTRAINT `fk_Filme_Genero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `Cinema`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `metodoPagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Trailer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Trailer` (
  `idTrailer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NOT NULL,
  `duracao` INT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (`idTrailer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Sessao` (
  `idSessao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `formato` VARCHAR(10) NOT NULL,
  `idioma` VARCHAR(10) NOT NULL,
  `idFilme` INT UNSIGNED NOT NULL,
  `idSala` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  PRIMARY KEY (`idSessao`),
  INDEX `fk_Sessao_Filme1_idx` (`idFilme`),
  INDEX `fk_Sessao_Sala1_idx` (`idSala`),
  CONSTRAINT `fk_Sessao_Filme1`
    FOREIGN KEY (`idFilme`)
    REFERENCES `Cinema`.`Filme` (`idFilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_Sala1`
    FOREIGN KEY (`idSala`)
    REFERENCES `Cinema`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Sessao_has_Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Sessao_has_Assento` (
  `idSessao` INT UNSIGNED NOT NULL,
  `idAssento` INT UNSIGNED NOT NULL,
  `ocupado` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSessao`, `idAssento`),
  INDEX `fk_Sessao_has_Assento_Assento1_idx` (`idAssento`),
  INDEX `fk_Sessao_has_Assento_Sessao1_idx` (`idSessao`),
  CONSTRAINT `fk_Sessao_has_Assento_Sessao1`
    FOREIGN KEY (`idSessao`)
    REFERENCES `Cinema`.`Sessao` (`idSessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sessao_has_Assento_Assento1`
    FOREIGN KEY (`idAssento`)
    REFERENCES `Cinema`.`Assento` (`idAssento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Ingresso` (
  `idIngresso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `idCliente` INT UNSIGNED NOT NULL,
  `idSessao` INT UNSIGNED NOT NULL,
  `idAssento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idIngresso`),
  INDEX `fk_Ingresso_Cliente1_idx` (`idCliente`),
  INDEX `fk_Ingresso_Sessao_has_Assento1_idx` (`idSessao`, `idAssento`),
  CONSTRAINT `fk_Ingresso_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Cinema`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Sessao_has_Assento1`
    FOREIGN KEY (`idSessao` , `idAssento`)
    REFERENCES `Cinema`.`Sessao_has_Assento` (`idSessao` , `idAssento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`Trailer_has_Sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`Trailer_has_Sessao` (
  `idTrailer` INT UNSIGNED NOT NULL,
  `idSessao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idTrailer`, `idSessao`),
  INDEX `fk_Trailer_has_Sessao_Sessao1_idx` (`idSessao`),
  INDEX `fk_Trailer_has_Sessao_Trailer1_idx` (`idTrailer`),
  CONSTRAINT `fk_Trailer_has_Sessao_Trailer1`
    FOREIGN KEY (`idTrailer`)
    REFERENCES `Cinema`.`Trailer` (`idTrailer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trailer_has_Sessao_Sessao1`
    FOREIGN KEY (`idSessao`)
    REFERENCES `Cinema`.`Sessao` (`idSessao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
